<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxT9mRz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxT9mRz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxT9mRz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxT9mRz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAxT9mRz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AxT9mRz',
    'container.build_id' => '3da47add',
    'container.build_time' => 1593438208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxT9mRz');
