<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9zKfut4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9zKfut4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9zKfut4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9zKfut4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9zKfut4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9zKfut4',
    'container.build_id' => '2c4cff0a',
    'container.build_time' => 1593395815,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9zKfut4');
